#!/bin/bash
rm -rf dist
export PYTHONHASHSEED=22
VERSION=`git describe --tags`
pyinstaller --noconfirm --ascii --name $VERSION contrib/osx.spec
hdiutil create -fs HFS+ -volname "Electrum-LBTC" -srcfolder dist/Electrum-LBTC.app dist/electrum-lbtc-$VERSION.dmg
